diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name='inquiry'),
    path('diary-list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('diary-create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),

]

private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバでメディアを配信できるようにする設定

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.

class Diary(models.Model):
    """日記モデル"""

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True)
    photo1 = models.ImageField(verbose_name='写真1',blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2',blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3',blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

        def __str__(self):
            return self.title

diary/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
from .models import Diary


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = '問い合わせ {}'.format(title)
        message = '送信者名:{0}\nメールアドレス:{1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list  = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ("title", "content", "photo1", "photo2", "photo3",)

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.value():
                field.widget.attrs['class']='form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
import logging
from django.contrib import messages
from django.views import generic
from .forms import InquiryForm, DiaryCreateForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Diary
from django.shortcuts import get_object_or_404
# Create your views here.

logger = logging.getLogger(__name__)


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # URLに埋め込まれた主キーから日記データを１件取得
        diary = get_object_or_404(Diary, pk=self.kwargs['pk'])
        # ログインユーザーと日記を比較し、異なればraise_exceptionの設定に従う
        return self.request.user == diary.user


class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 2


    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

class DiaryDetailView(LoginRequiredMixin, OnlyYouMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '日記の作成に失敗しました。')
        return super().form_invalid(form)

class DiaryUpdateView(LoginRequiredMixin, OnlyYouMixin, generic.UpdateView):
    model=Diary
    template_name = 'diary_update.html'

    def get_success_url(self):
        return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '日記の更新に失敗しました')
        return super().form_invalid(form)

class DiaryDeleteView(LoginRequiredMixin, OnlyYouMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '日記を削除しました。')
        return super().delete(request, *args, **kwargs)

accounts/templates/email_confirm.html
{% extends 'base.html' %}

{% block title %}Confirm sign up | Private Diary{% endblock %}

{% block active_login %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>ユーザー登録</h1>

            {% if confirmation %}

                <p>ユーザー登録を確定するには、以下のボタンを押してください。</p>

                <form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">確定</button>
                </form>

            {% else %}

                {% url 'account_email' as email_url %}

                <p>リンクの有効期限が過ぎています。 <a href="{{ email_url }}">再申請</a>.</p>

            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Log In | Private Diary{% endblock %}

{% block active_login %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>ログイン</h1>
            <form method="post" action="{% url 'account_login' %}">
                {% csrf_token %}

                <div class="mb-4 col-4">
                    {% bootstrap_form form %}
                </div>

                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}

                <button class="btn btn-primary" type="submit">ログイン</button>
                <p><a class="button secondaryAction" href="{% url 'account_reset_password' %}">パスワードを忘れましたか？</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}パスワードリセット | Private Diary{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>パスワードリセット</h1>
            {% if user.is_authenticated %}
            {% include "account/snippets/already_logged_in.html" %}
            {% endif %}

            <p>パスワードリセット用メールを送信します。</p>

            <form method="post" action="{% url 'account_reset_password' %}">
                {% csrf_token %}

                <div class="mb-4 col-4">
                    {% bootstrap_form form %}
                </div>

                <button class="btn btn-primary" type="submit">送信</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password reset done | Private Diary{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>パスワードリセット</h1>

            {% if user.is_authenticated %}
            {% include "account/snippets/already_logged_in.html" %}
            {% endif %}

            <p>パスワードリセット用のメールを送信しました。</p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_from_key.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}パスワードリセット | Private Diary{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>{% if token_fail %}不正トークン{% else %}パスワードリセット{% endif %}</h1>

            {% if token_fail %}
            {% url 'account_reset_password' as passwd_reset_url %}
            <p>このパスワードリセット用リンクは無効になっています。 <a href="{{ passwd_reset_url }}">パスワードリセット再申請</a></p>
            {% else %}
            {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}

                <div class="mb-4 col-4">
                    {% bootstrap_form form %}
                </div>

                <button class="btn btn-primary" type="submit">変更</button>
            </form>
            {% else %}
            <p>パスワードは変更されています。</p>
            {% endif %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_from_key_done.html
{% extends 'base.html' %}

{% block title %}Change Password | Private Diary{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>パスワード変更</h1>
            <div class="mt-4">
                <p>パスワードが変更されました。</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}サインアップ|Private Diary{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">

            <h1>サインアップ</h1>
            <form method="post" action="{% url'account_signup %}">
                {% csrf_token %}

                <div class="mb-4 col-4">
                    {% bootstrap_form form %}
                </div>

                {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value}}" />
                {% endif %}

                <button class="btn-primary" type="submit">登録</button>
            </form>
        </div>
    </div>
</div>

accounts/templates/verification_sent.html
{% extends 'base.html' %}

{% block title %}Verify Your E-mail Address | Private Diary{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h1>メールアドレスを確認してください</h1>
            <div class="mt-5">
                <p>確認のメールを送信しました。</p>
                <p>メールに記載されたリンクをクリックして、ユーザー登録を完了させてください。数分待っても確認のメールが届かない場合はご連絡ください。</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
          rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet"/>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet"/>

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>

<body>
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% block active_diary_list %}{% endblock %}"
                           href="{% url 'diary:diary_list' %}">DIARY LIST</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">Log In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block header%}{% endblock %}

    {% if messages %}
    <div class="container my-div-style">
        <div class="row">
            <ul class="messages" style="list-style: none;">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

    {% block contents%}{% endblock %}

    <!-- Footer -->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy 2021</p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
</div>
</body>
</html>

diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/diary_delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">Man must explore, and this is exploration at its greatest</h2>
                            <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 24, 2022
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="post.html"><h2 class="post-title">I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.</h2></a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 18, 2022
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">Science has not yet mastered prophecy</h2>
                            <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the next ten.</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on August 24, 2022
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">Failure is not an option</h2>
                            <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to future generations.</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on July 8, 2022
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
            </div>
            {% for diary in diary_list %}
            <div class="post-preview">
                <a href="{% url 'diary:diary_detail' diary.pk %}">
                    <h2 class="post-title">
                        {{ diary.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ diary.content|truncatechars:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ diary.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}